[build]
  functions = "netlify/functions"
  publish = "."

[[headers]]
  for = "/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Headers = "Content-Type"
    Access-Control-Allow-Methods = "POST, OPTIONS"

[[headers]]
  for = "/sitemap.xml"
  [headers.values]
    Content-Type = "application/xml"

[[redirects]]
  from = "/app"
  to = "/app/index.html"
  status = 200
  force = true

[[redirects]]
  from = "/wv"
  to = "/wv/index.html"
  status = 200
  force = true
